// @/db/productRepository.ts
import { getDb } from './dbManager';
import { Product, ProductType, Supplier } from '@/pos/types'; // Assuming Branch is also in types if needed for product context

// Helper to convert DB row to Product (handling potential JSON parsing if we stored complex fields as JSON)
// For now, product fields are mostly direct mappings.
const rowToProduct = (row: any): Product => {
  return {
    ...row,
    // Ensure numeric types are correct if they come from DB as something else
    purchasePrice: Number(row.purchasePrice),
    sellingPrice: Number(row.sellingPrice),
    stockQuantity: Number(row.stockQuantity),
    lowStockThreshold: row.lowStockThreshold !== null ? Number(row.lowStockThreshold) : undefined,
    taxRate: row.taxRate !== null ? Number(row.taxRate) : undefined,
  } as Product;
};


export const dbGetAllProducts = (): Product[] => {
  const db = getDb();
  const stmt = db.prepare('SELECT * FROM products');
  const rows = stmt.all();
  return rows.map(rowToProduct);
};

export const dbGetProductById = (id: string): Product | undefined => {
  const db = getDb();
  const stmt = db.prepare('SELECT * FROM products WHERE id = ?');
  const row = stmt.get(id);
  return row ? rowToProduct(row) : undefined;
};

export const dbAddProduct = (product: Product): Product => {
  const db = getDb();
  // Using INSERT OR REPLACE to handle cases where a product with the same ID might be added (e.g., during sync)
  // For a simple add, usually, ID would be generated by DB or checked for existence first.
  // Given product.id is already typically a uuidv4 from mock or API, this is more like an upsert.
  const stmt = db.prepare(`
    INSERT OR REPLACE INTO products (
      id, name, sku, barcode, category, purchasePrice, sellingPrice,
      stockQuantity, lowStockThreshold, taxRate, imageUrl,
      productTypeId, supplierId, branchId, lastStocktakeDate, notes
    ) VALUES (
      @id, @name, @sku, @barcode, @category, @purchasePrice, @sellingPrice,
      @stockQuantity, @lowStockThreshold, @taxRate, @imageUrl,
      @productTypeId, @supplierId, @branchId, @lastStocktakeDate, @notes
    )
  `);

  try {
    stmt.run({
      ...product,
      lowStockThreshold: product.lowStockThreshold ?? null, // Ensure undefined becomes null for DB
      taxRate: product.taxRate ?? null,
      barcode: product.barcode ?? null,
      imageUrl: product.imageUrl ?? null,
      productTypeId: product.productTypeId ?? null,
      supplierId: product.supplierId ?? null,
      branchId: product.branchId ?? null,
      lastStocktakeDate: product.lastStocktakeDate ?? null,
      notes: product.notes ?? null,
    });
    return product; // Return the input product as it was successfully inserted/replaced
  } catch (error) {
    console.error(`[ProductRepository] Error in dbAddProduct for ID ${product.id}:`, error);
    throw error;
  }
};

// For batch inserting/replacing products, e.g., during initial sync
export const dbUpsertProductsBatch = (products: Product[]): void => {
  const db = getDb();
  const insert = db.prepare(`
    INSERT OR REPLACE INTO products (
      id, name, sku, barcode, category, purchasePrice, sellingPrice,
      stockQuantity, lowStockThreshold, taxRate, imageUrl,
      productTypeId, supplierId, branchId, lastStocktakeDate, notes
    ) VALUES (
      @id, @name, @sku, @barcode, @category, @purchasePrice, @sellingPrice,
      @stockQuantity, @lowStockThreshold, @taxRate, @imageUrl,
      @productTypeId, @supplierId, @branchId, @lastStocktakeDate, @notes
    )
  `);

  const upsertMany = db.transaction((items: Product[]) => {
    for (const item of items) {
      try {
        insert.run({
          ...item,
          lowStockThreshold: item.lowStockThreshold ?? null,
          taxRate: item.taxRate ?? null,
          barcode: item.barcode ?? null,
          imageUrl: item.imageUrl ?? null,
          productTypeId: item.productTypeId ?? null,
          supplierId: item.supplierId ?? null,
          branchId: item.branchId ?? null,
          lastStocktakeDate: item.lastStocktakeDate ?? null,
          notes: item.notes ?? null,
        });
      } catch (error) {
        console.error(`[ProductRepository] Error upserting product ID ${item.id} in batch:`, error);
        // Decide on error handling: throw, log and continue, collect errors?
        // For now, log and continue.
      }
    }
  });

  try {
    upsertMany(products);
    console.log(`[ProductRepository] Batch upsert of ${products.length} products successful.`);
  } catch (error) {
    console.error('[ProductRepository] Error in dbUpsertProductsBatch transaction:', error);
    throw error;
  }
};


export const dbUpdateProduct = (productId: string, productUpdateData: Partial<Omit<Product, 'id'>>): Product | undefined => {
  const db = getDb();

  // Fetch current product to merge, as better-sqlite3's update doesn't easily do partial updates with dynamic fields
  const currentProduct = dbGetProductById(productId);
  if (!currentProduct) {
    console.warn(`[ProductRepository] Product with ID ${productId} not found for update.`);
    return undefined;
  }

  const updatedProductData = { ...currentProduct, ...productUpdateData };

  const stmt = db.prepare(`
    UPDATE products
    SET name = @name, sku = @sku, barcode = @barcode, category = @category,
        purchasePrice = @purchasePrice, sellingPrice = @sellingPrice, stockQuantity = @stockQuantity,
        lowStockThreshold = @lowStockThreshold, taxRate = @taxRate, imageUrl = @imageUrl,
        productTypeId = @productTypeId, supplierId = @supplierId, branchId = @branchId,
        lastStocktakeDate = @lastStocktakeDate, notes = @notes
    WHERE id = @id
  `);

  try {
    const result = stmt.run({
      ...updatedProductData,
      id: productId, // ensure id is part of the bound parameters for WHERE clause
      lowStockThreshold: updatedProductData.lowStockThreshold ?? null,
      taxRate: updatedProductData.taxRate ?? null,
      barcode: updatedProductData.barcode ?? null,
      imageUrl: updatedProductData.imageUrl ?? null,
      productTypeId: updatedProductData.productTypeId ?? null,
      supplierId: updatedProductData.supplierId ?? null,
      branchId: updatedProductData.branchId ?? null,
      lastStocktakeDate: updatedProductData.lastStocktakeDate ?? null,
      notes: updatedProductData.notes ?? null,
    });

    if (result.changes > 0) {
      return dbGetProductById(productId); // Fetch the updated product to return it
    }
    return undefined; // No rows updated (should not happen if currentProduct was found)
  } catch (error) {
    console.error(`[ProductRepository] Error in dbUpdateProduct for ID ${productId}:`, error);
    throw error;
  }
};

export const dbDeleteProduct = (productId: string): boolean => {
  const db = getDb();
  const stmt = db.prepare('DELETE FROM products WHERE id = ?');
  try {
    const result = stmt.run(productId);
    return result.changes > 0;
  } catch (error) {
    console.error(`[ProductRepository] Error in dbDeleteProduct for ID ${productId}:`, error);
    throw error;
  }
};

// TODO: Add similar repositories for product_types, suppliers, branches if they need to be managed locally from a remote source.
// For now, they are only referenced by products. If we need to populate dropdowns from DB for these,
// then we'd need `dbGetAllProductTypes`, etc., and sync logic for them in `syncService`.
// The `mockProductTypes` are currently imported directly in forms.
// It's assumed `product_types`, `suppliers`, `branches` tables are populated manually or by a different sync process for now.
// Or, they could be synced along with products if product data from API includes full objects for these.
// For simplicity, this milestone focuses on products and invoices being the primary synced entities.


// === Reporting Functions for Products ===

export interface InventoryReportItemData extends Product {
  totalValueAtCost: number;
  totalValueAtSellingPrice: number;
}

export interface InventoryReportSummary {
  totalItemsCount: number; // Sum of all stockQuantities
  totalUniqueProducts: number;
  overallTotalValueAtCost: number;
  overallTotalValueAtSellingPrice: number;
  items: InventoryReportItemData[];
}

export const dbGetInventoryReportData = (branchId?: string): InventoryReportSummary => {
  const db = getDb();
  let query = 'SELECT * FROM products';
  const params: any[] = [];
  if (branchId) {
    query += ' WHERE branchId = ?';
    params.push(branchId);
  }

  const products: Product[] = db.prepare(query).all(...params).map(rowToProduct);

  let totalItemsCount = 0;
  let overallTotalValueAtCost = 0;
  let overallTotalValueAtSellingPrice = 0;

  const reportItems: InventoryReportItemData[] = products.map(p => {
    const valueAtCost = p.stockQuantity * p.purchasePrice;
    const valueAtSelling = p.stockQuantity * p.sellingPrice;

    totalItemsCount += p.stockQuantity;
    overallTotalValueAtCost += valueAtCost;
    overallTotalValueAtSellingPrice += valueAtSelling;

    return {
      ...p,
      totalValueAtCost: valueAtCost,
      totalValueAtSellingPrice: valueAtSelling,
    };
  });

  return {
    totalItemsCount,
    totalUniqueProducts: products.length,
    overallTotalValueAtCost,
    overallTotalValueAtSellingPrice,
    items: reportItems,
  };
};

export const dbGetLowStockItems = (branchId?: string): Product[] => {
  const db = getDb();
  // Assumes lowStockThreshold > 0 means it's set.
  // Products where stockQuantity <= lowStockThreshold
  let query = 'SELECT * FROM products WHERE stockQuantity <= lowStockThreshold AND lowStockThreshold > 0';
  const params: any[] = [];
  if (branchId) {
    query += ' AND branchId = ?';
    params.push(branchId);
  }

  const rows = db.prepare(query).all(...params);
  return rows.map(rowToProduct);
};
