import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'prod_001',
    name: 'Men\'s Classic T-Shirt - White',
    sku: 'MTS001-WH',
    barcode: '1234567890123',
    category: 'Men/Apparel/T-Shirts',
    purchasePrice: 80,
    sellingPrice: 150,
    stockQuantity: 50,
    lowStockThreshold: 10,
    taxRate: 0.14, // 14% VAT
    imageUrl: 'https://via.placeholder.com/100?text=White+T-Shirt',
  },
  {
    id: 'prod_002',
    name: 'Men\'s Classic T-Shirt - Black',
    sku: 'MTS001-BK',
    barcode: '1234567890124',
    category: 'Men/Apparel/T-Shirts',
    purchasePrice: 80,
    sellingPrice: 150,
    stockQuantity: 45,
    lowStockThreshold: 10,
    taxRate: 0.14,
    imageUrl: 'https://via.placeholder.com/100?text=Black+T-Shirt',
  },
  {
    id: 'prod_003',
    name: 'Women\'s Slim Fit Jeans - Blue',
    sku: 'WSJ002-BL',
    barcode: '1234567890125',
    category: 'Women/Apparel/Jeans',
    purchasePrice: 250,
    sellingPrice: 450,
    stockQuantity: 30,
    lowStockThreshold: 5,
    taxRate: 0.14,
    imageUrl: 'https://via.placeholder.com/100?text=Blue+Jeans',
  },
  {
    id: 'prod_004',
    name: 'Leather Belt - Brown',
    sku: 'ACC003-BR',
    barcode: '1234567890126',
    category: 'Accessories/Belts',
    purchasePrice: 120,
    sellingPrice: 280,
    stockQuantity: 60,
    lowStockThreshold: 15,
    taxRate: 0.14,
    imageUrl: 'https://via.placeholder.com/100?text=Leather+Belt',
  },
  {
    id: 'prod_005',
    name: 'Sports Cap - Red',
    sku: 'ACC004-RD',
    barcode: '1234567890127',
    category: 'Accessories/Caps',
    purchasePrice: 60,
    sellingPrice: 120,
    stockQuantity: 75,
    lowStockThreshold: 20,
    taxRate: 0.0, // Tax-exempt example
    imageUrl: 'https://via.placeholder.com/100?text=Red+Cap',
  },
  {
    id: 'prod_006',
    name: 'Kids Summer Dress - Floral',
    sku: 'KSD005-FL',
    barcode: '1234567890128',
    category: 'Kids/Apparel/Dresses',
    purchasePrice: 150,
    sellingPrice: 320,
    stockQuantity: 25,
    lowStockThreshold: 5,
    taxRate: 0.14,
    imageUrl: 'https://via.placeholder.com/100?text=Floral+Dress',
  }
];
